lib/bundler/audit/scanner.rb

Many organizations have references to internal git repositories in their
`Gemfile`s. Allow these repositories to be treated as safe since they
are resolvable only internally, and are controlled by the organization.
Closes #72

Treat internal git/http hosts as secure

---

lib/bundler/audit/database.rb

When a user of `bundler-audit` has the following in his `~/.gitconfig`
```
[log]
date = relative
```
...then `bundle-audit update` and subsequent `bundle-audit` would fail with 
```
/usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/time.rb:327:in `parse': no time information in "2 days ago\n" (ArgumentError)
from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-audit-0.3.1/lib/bundler/audit/database.rb:71
```
This PR forces the `git` invocation to use ISO8601 formatting which can be correctly parsed by Ruby's Time class.

Force git to use iso8601 dates explicitly for repo modification times

---

lib/bundler/audit/scanner.rb

Like having a git:// route on a local network, having an insecure route to a gem server should be allowed. In our case we're running gem-in-a-box.

Allow insecure gem source if it lives on a private network.

---

README.md
lib/bundler/audit/cli.rb

I've integrated bundler-audit into our CI (it's fantastic btw, thanks for all the work on this).
However, it's difficult to run more than one command at a time. Right now I'm solving this with a script which runs `bundle-audit update && bundle-audit check`, but I figured it would make sense to natively support the option to update the database and run a check in a single command.
Let me know what you think.

Add option to update before running check

---

lib/bundler/audit/database.rb

This allow `update` to work if the directory already exists.

Only try to do a git pull if ".git" exists

---

lib/bundler/audit/advisory.rb
spec/advisory_spec.rb

The yamls from [ruby-advisory-db](https://github.com/rubysec/ruby-advisory-db) have `date` ([example](https://github.com/rubysec/ruby-advisory-db/blob/master/gems/nokogiri/CVE-2015-1819.yml#L6)). Seems missing from advisory. This Pull Request adds `date` to `Advisory`.

Include date in advisory object

---

README.md
bin/bundler-audit
spec/integration_spec.rb

When a user runs `bundle COMMAND` and Bundler does not include COMMAND, it tries to run an executable named `bundler-COMMAND`.
This commit exploits this behavior and allows the user to run `bundle audit` to run bundler-audit.

Run as external Bundler command

---

gemspec.yml

…to allow automatic license checks.
See https://spdx.org/licenses/
[skip ci]

use SPDX-compatible license name

---

ChangeLog.md
README.md
lib/bundler/audit/cli.rb
lib/bundler/audit/database.rb
spec/cli_spec.rb
spec/database_spec.rb

Hi Hal. This implements https://github.com/rubysec/bundler-audit/issues/164
I couldn't find development instructions, so I hope I'm adding tests in the right place, and following the project style. I get a few test failures locally that seem unrelated to my work, and I'm hoping they pass on CI.

Add --quiet option to `check` and `update` commands

---

lib/bundler/audit/advisory.rb
lib/bundler/audit/cli.rb
lib/bundler/audit/scanner.rb
spec/advisory_spec.rb
spec/bundle/unpatched_gems/Gemfile
spec/scanner_spec.rb

This PR extends `bundle audit` so it will report GitHub Security Advisories, in addition to the CVEs and OSVDB advisories it already reports.
I did some very mild refactoring, adding a `has_supported_identifier?` method to contain some stray logic.  I considered doing more extensive refactoring,  but in the end decided to keep the change minimal for now.
- This PR adds the first GHSA into rubysec/advisory-db: https://github.com/rubysec/ruby-advisory-db/pull/397
- And some discussion noting the need to also extend bundler-audit, as is done here: https://github.com/rubysec/ruby-advisory-db/pull/397#issuecomment-507946376
This is what a GHSA report looks like:
```
$  bundle audit
Name: yard
Version: 0.9.19
Advisory: GHSA-xfhh-rx56-rxcr
Criticality: Unknown
URL: …
```

Bundle audit extended to report GitHub Security Advisories (GHSAs)

---

lib/bundler/audit/database.rb
spec/spec_helper.rb

Hi!  I'm working on using your project to help with semi-automated updates of ruby packages in the nixpkgs package repository (nixos/nixpkgs#64822).  I noticed that I consistently saw this error when I ran my script for several packages concurrently:
```
fatal: Cannot rebase onto multiple branches.
Failed updating ruby-advisory-db!
```
I was able to fix the problem by removing this from my `~/.gitconfig`:
```
[pull]
rebase = true
```
So I think this change would help my edge case, without bothering anyone else.

Specify `--no-rebase` when updating database

---

README.md

I fix the link or the travis -ci yml and also reorder the badges to make them easier visible.

fix travis ci link and reorder links in readme

---

lib/bundler/audit/scanner.rb

Trying to use bundler-audit with Bundler 2.1.1 fails because
`Scanner#internal_source?` gets passed a `Bundler::URI::HTTP` instance.
```
uri/common.rb:745:in `URI': bad argument (expected URI object or URI string) (ArgumentError)
```
This patch uses `#to_s` on the passed object to work around that issue.

Fix Scanner#internal_source? w/ Bundler::URI::HTTP

---

README.md
gemspec.yml

Thor changelog:
https://github.com/erikhuda/thor/blob/master/CHANGELOG.md

Update thor version

---

lib/bundler/audit/task.rb

Refactors Rake task so you don't need to loop over `%w(update check)`, it directly passes the `--update` option

Refactor Rake task

---

.travis.yml

https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

ruby 2.3 EOL deprecated

---

lib/bundler/audit/cli.rb
spec/cli_spec.rb

Our CircleCI build was passing (and failing silently) when running bundle-audit since we were not passing the right arguments to the `start` method.
Now when we run our custom bundler audit Rake task, which uses the CLI directly, we get a non-zero exit error when we pass the wrong arguments:
Without this PR:
```
➜  bundle exec rake bundle:audit
ERROR: "rake check" was called with arguments ["--ignore CVE-2015-9284"]
Usage: "rake check"
➜ echo $?
0
```
With this PR:
```
➜  bundle exec rake bundle:audit
ERROR: "rake check" was called with arguments ["--ignore CVE-2015-9284"]
Usage: "rake check"
➜ echo $?
127
```

Use non-zero exit code if there's an argument error when running through CLI

---

README.md

Hei ya team, 
I got an error saying that `Git is not installed!`
And I realized that:
1. There is a current issue with this: https://github.com/rubysec/bundler-audit/issues/267
2. In the requirement, git is not listed as part of it
We also assumed that this gem does not require git to run, so now our deployment is a little bit broken with the latest version.
By adding git as part of the requirement I believe will help the other developers in the future.
Cheers

Doc: Add git as part of the requirement

---

.travis.yml

https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/

support for ruby 2.4 has ended

---

lib/bundler/audit/scanner.rb

We use a local loopback address to serve our custom gems before vendorizing them. Yes, we could use a FS path, but that leads to conflicts across different developer machines.
PR #90 treats internal git/http hosts as secure. „internal“ roughly means „RFC1918 address“ there. I propose extending this definition to local loopback addresses.
Minimal example:
```sh
mkdir -p repo/gems
gem generate_index --directory repo
cd repo
ruby -rwebrick -e'WEBrick::HTTPServer.new(BindAddress: "localhost", Port: 8808, DocumentRoot: Dir.pwd).start'
```
I also set the version number to `0.5.0.1`. Tell me, if you want me to remove that commit.
Thanks for sharing `bundler-audit`!
Alex

Treat 127.0.0.0/8 and ::1/128 sources as secure

---

README.md

Fix `[git]` and `[bundler]` link references.
See each commit for details.

Docs: Fix README link reference

---

lib/bundler/audit/advisory.rb

I changed `YAML.load_file` to `YAML.safe_load` because it can deserialize unexpected classes.
RCE can occur if there are no restrictions on the classes that can be deserialized, if the ruby-advisory-db git repository contains a specially crafted yaml file, or if it is crafted into a local cache.
FYI https://gist.github.com/staaldraad/89dffe369e1454eedd3306edc8a7e565

Use YAML.safe_load

---

lib/bundler/audit/cli/formats/text.rb
spec/cli/formats/text_spec.rb
spec/fixtures/advisory/CVE-2020-1234.yml

Since version **v0.8.0**, the default output (text) of the CLI is impacted by a regression.
Advisories with CVSS v3 scores have a broader range of Criticality values than with CVSS v2. `None` and `Critical` values are currently missing from the `print_advisory` method in [lib/bundler/audit/cli/formats/text.rb](https://github.com/rubysec/bundler-audit/blob/v0.8.0/lib/bundler/audit/cli/formats/text.rb#L79-L85).
This PR adds cvss_v3 value to the fixture and ensure to test output for both v2 and v3 values. This is a simle fix which keeps current architecture as is but it might be welcome to have a single place where Criticality values are defined and how they should be printed, to avoid such discrepancy in the future.
Thanks.

Fix text format output 

---

lib/bundler/audit/advisory.rb
lib/bundler/audit/cli/formats/json.rb
spec/advisory_spec.rb
spec/cli/formats/json_spec.rb
spec/results/unpatched_gem_spec.rb

Currently, the criticality information is missing when tried to generate the report in JSON format.
I've updated the format/json.rb to show criticality level.
fixes: #308

Add criticality level in JSON format

---

lib/bundler/audit/cli/formats/junit.rb

Sorry I forgot to fully test my changes in #314 without the
development dependencies. It seems the `yard` gem which is used during
tests, [requires the `cgi` library](https://github.com/lsegal/yard/blob/359006641260eef1fe6d28f5c43c7c98d40f257d/lib/yard/templates/helpers/html_helper.rb#L2) so this was not catched during
automatic unit tests.
This fixes the use of the gem as a binary.

fix: require CGI lib explicitly

---

.github/workflows/ruby.yml
bundler-audit.gemspec
lib/bundler/audit/cli.rb
lib/bundler/audit/scanner.rb
spec/advisory_spec.rb
spec/database_spec.rb

In addition to the CI configuration change this PR makes the following changes:
* Fixes YAML load in specs to permit Date
* Limits number of commit logs passed to Time.parse in spec so the string is less than 128 characters
* Adds the MFA requirement to Rubygems publishing to satisfy Rubocop
* A few formatting changes to satisfy Rubocop

Add Ruby 3.1 to CI

---

lib/bundler/audit/cli/formats/junit.rb
lib/bundler/audit/cli/formats/text.rb
spec/cli/formats/junit_spec.rb
spec/cli/formats/text_spec.rb

Suggesting a change to the separator of multiple patched versions in the `Solution:` line. The reason being that the output for some CVEs may look very misleading. An example case is [this advisory](https://github.com/rubysec/ruby-advisory-db/blob/master/gems/actionpack/CVE-2022-23633.yml#L52) which uses a comma in the suggested constraint of the gem version. Currently, this leads the auditor to print out this line:
```
Solution: upgrade to ~> 5.2.6, >= 5.2.6.2, ~> 6.0.4, >= 6.0.4.6, ~> 6.1.4, >= 6.1.4.6, >= 7.0.2.2
```
This may trick the reader into thinking that either one can be chosen when really the suggestions are joined using a comma making it harder to discern them. This change uses the word `or` as the separator which should be more obvious to the reader.
```
Solution: upgrade to …
```

Use a less ambiguous separator for the version update suggestions

---

lib/bundler/audit/cli/formats/junit.rb
lib/bundler/audit/cli/formats/text.rb
spec/cli/formats/junit_spec.rb
spec/cli/formats/text_spec.rb

Wrapping the suggested patched version in quotes provides better separation and readability.
Original suggestion:
https://github.com/rubysec/bundler-audit/pull/327#issuecomment-1055666267
@postmodern

Wrap suggested patched versions in quotes

---

README.md

Pr. https://github.com/rubysec/bundler-audit/issues/178 the parameter is --gemfile-lock

Fixes --gemfile-lock example in readme.md

---

gemspec.yml

As listed in https://spdx.org/licenses/, the license identifier `GPL-3.0+` is deprecated. 
I replaced it with `GPL-3.0-or-later`, in order to follow the SPDX specification.
Also, I changed the `license` key in `gemspec.yml`, to `licenses`, in order to match [naming in gem specification](https://guides.rubygems.org/specification-reference/).

Fix licenses spec

---

bundler-audit.gemspec
gemspec.yml

Currently, while `gemspec.yml` includes metadata links for documentation, issue tracker, and other, the section is not used in the gemspec. This change corrects that.
In addition, I have noticed that the links are incorrect and point to no longer relevant repository name `bundler-audit.rb`.
On the [RubyGems page](https://rubygems.org/gems/bundler-audit), most of the links were inferred from `homepage`, so there is a link to source code and documentation and the only on missing is "Changelog".
To test, I built the gem with rake build and compared the listing before and after the change:
```bash
tar -xOzf pkg/bundler-audit-0.9.2.gem metadata.gz | gunzip
```
Full diff:
```diff
--- before.txt	2024-09-12 07:08:08
+++ after.txt	2024-09-12 07:07:32
@@ -129,6 +129,10 @@
licenses:
- …
```

Added gem metadata and corrected links in gemspec.yml
